import type { CuratedApiEntry } from "./api-hub-types";

/** Additional curated public HTTPS endpoints (no API keys). Merged into the hub catalog. */
export const API_HUB_MORE_ENTRIES: CuratedApiEntry[] = [
  entry("pokeapi-pokemon", "PokeAPI — Pokémon by ID", "Games", "Species data for #1", "Official-style Pokémon REST API. Swap the numeric id in the path.", "https://pokeapi.co/api/v2/pokemon/1", "GET /api/v2/pokemon/{id}", '{"name":"bulbasaur","id":1,"height":7,"weight":69}', "{ name, id, height, weight, types[], stats[], … }"),
  entry("coincap-bitcoin", "CoinCap — asset quote", "Finance", "Live crypto spot metrics", "Public asset snapshot by id (e.g. bitcoin).", "https://api.coincap.io/v2/assets/bitcoin", "GET /v2/assets/{id}", '{"data":{"id":"bitcoin","rank":"1","symbol":"BTC","priceUsd":"…"}}', "{ data: { id, rank, symbol, priceUsd, … } }"),
  entry("quotable-random", "Quotable — random quote", "Fun", "Inspirational quotes JSON", "Random quotation with author and tags.", "https://api.quotable.io/random", "GET /random", '{"content":"…","author":"…","tags":["…"]}', "{ content, author, tags[] }"),
  entry("adviceslip-random", "Advice Slip — random advice", "Fun", "One-liner advice JSON", "Returns a slip id and short advice string.", "https://api.adviceslip.com/advice", "GET /advice", '{"slip":{"id":1,"advice":"…"}}', "{ slip: { id, advice } }"),
  entry("deckofcards-shuffle", "Deck of Cards — new deck", "Games", "Shuffled deck id", "Creates a shuffled deck; use deck_id for draws.", "https://deckofcardsapi.com/api/deck/new/shuffle/?deck_count=1", "GET /api/deck/new/shuffle/", '{"success":true,"deck_id":"…","remaining":52}', "{ success, deck_id, shuffled, remaining }"),
  entry("universities-search", "Universities — search by country", "Education", "Global university list", "Filter universities for a country name.", "https://universities.hipolabs.com/search?country=United%20States", "GET ?country=", '[{"name":"Harvard University","web_pages":["…"],"country":"United States"}]', "Array of { name, web_pages[], domains[], country }"),
  entry("worldtime-london", "World Time API — London", "Dev utilities", "IANA timezone payload", "Current local time and UTC offset for a zone.", "https://worldtimeapi.org/api/timezone/Europe/London", "GET /api/timezone/{region}/{city}", '{"timezone":"Europe/London","datetime":"…","utc_offset":"+00:00"}', "{ timezone, datetime, utc_offset, … }"),
  entry("github-zen", "GitHub — Zen text", "Dev utilities", "Plain-text aphorism", "Single line of text; no JSON.", "https://api.github.com/zen", "GET /zen", "Responsive design is good.", "text/plain line"),
  entry("xkcd-current", "xkcd — current comic", "Entertainment", "Comic metadata JSON", "Latest comic number, title, image URL, alt text.", "https://xkcd.com/info.0.json", "GET /info.0.json", '{"num":1234,"title":"…","img":"https://…","alt":"…"}', "{ num, title, img, alt, … }"),
  entry("chuck-norris-joke", "Chuck Norris — random joke", "Fun", "ICNDb-style JSON", "Random joke object with icon and id.", "https://api.chucknorris.io/jokes/random", "GET /jokes/random", '{"icon_url":"…","id":"…","value":"…"}', "{ icon_url, id, value }"),
  entry("bored-activity", "Bored API — random activity", "Fun", "Beat boredom JSON", "Suggests an activity with type and participants.", "https://www.boredapi.com/api/activity", "GET /api/activity", '{"activity":"…","type":"education","participants":1}', "{ activity, type, accessibility, participants, … }"),
  entry("nager-holidays-us", "Nager.Date — US public holidays", "Geography", "Official holiday list", "Public holidays for a calendar year (ISO country code).", "https://date.nager.at/api/v3/PublicHolidays/2024/US", "GET /api/v3/PublicHolidays/{year}/{country}", '[{"date":"2024-01-01","localName":"…","name":"…"}]', "Array of { date, localName, name, … }"),
  entry("zippopotam-us", "Zippopotam — US ZIP metadata", "Geography", "ZIP → place names", "Lookup city and state for a US ZIP.", "https://api.zippopotam.us/us/90210", "GET /{country}/{zip}", '{"country":"United States","places":[{"place name":"Beverly Hills"}]}', "{ country, places: [{ place name, state, … }] }"),
  entry("openlibrary-search", "Open Library — search", "Books", "Book search JSON", "Search works by query string.", "https://openlibrary.org/search.json?q=the+lord+of+the+rings&limit=1", "GET /search.json?q=&limit=", '{"numFound":123,"docs":[{"title":"…","author_name":["…"]}]}', "{ numFound, docs: [{ title, author_name, … }] }"),
  entry("itunes-search", "iTunes Search API", "Entertainment", "Media lookup", "Search Apple’s catalog (tracks, albums, etc.).", "https://itunes.apple.com/search?term=jack+johnson&limit=1", "GET ?term=&limit=", '{"resultCount":1,"results":[{"trackName":"…","artistName":"…"}]}', "{ resultCount, results[] }"),
  entry("github-user-octocat", "GitHub — user profile", "Dev utilities", "Public user JSON", "Read-only public fields for a username.", "https://api.github.com/users/octocat", "GET /users/{login}", '{"login":"octocat","id":583231,"public_repos":8}', "{ login, id, avatar_url, public_repos, … }"),
  entry("blockchain-ticker", "Blockchain.com — ticker", "Finance", "Multi-currency BTC rates", "Spot prices in several fiat codes.", "https://blockchain.info/ticker", "GET /ticker", '{"USD":{"15m":65000,"symbol":"$"}}', "{ [currency]: { 15m, last, symbol, … } }"),
  entry("genderize-extra", "Genderize.io — gender guess", "Identity", "Probable gender from name", "Statistical guess; not for sensitive use.", "https://api.genderize.io?name=peter", "GET ?name=", '{"name":"peter","gender":"male","probability":0.99,"count":123}', "{ name, gender, probability, count }"),
  entry("zenquotes-today", "ZenQuotes — quote of the day", "Fun", "Daily quote array", "Returns an array with one quote object.", "https://zenquotes.io/api/today", "GET /api/today", '[{"q":"…","a":"Author"}]', "[{ q, a, h? }]"),
  entry("lyrics-ovh-sample", "Lyrics.ovh — lyrics snippet", "Entertainment", "Song lyrics lookup", "Artist and title in path; may 404 for missing tracks.", "https://api.lyrics.ovh/v1/coldplay/yellow", "GET /v1/{artist}/{title}", '{"lyrics":"Look at the stars…"}', "{ lyrics: string }"),
  entry("rick-morty-char", "Rick and Morty API — character", "Entertainment", "Character by id", "Episode list and origin URLs for a character.", "https://rickandmortyapi.com/api/character/1", "GET /api/character/{id}", '{"id":1,"name":"Rick Sanchez","status":"Alive","species":"Human"}', "{ id, name, status, species, episode[], … }"),
  entry("datamuse-words", "Datamuse — word search", "Dev utilities", "Vocabulary suggestions", "Pattern or meaning-based word list.", "https://api.datamuse.com/words?sp=b*&max=5", "GET ?sp=&max=", '[{"word":"big","score":…}]', "Array of { word, score, … }"),
  entry("opentdb-question", "Open Trivia DB — one question", "Games", "Trivia JSON", "URL-encoded categories and difficulty optional.", "https://opentdb.com/api.php?amount=1&type=multiple", "GET ?amount=&type=", '{"response_code":0,"results":[{"question":"…","correct_answer":"…"}]}', "{ response_code, results[] }"),
  entry("artic-artwork", "Art Institute of Chicago — artwork", "Art", "Museum object JSON", "Single artwork with image iiif id.", "https://api.artic.edu/api/v1/artworks/129884", "GET /api/v1/artworks/{id}", '{"data":{"id":129884,"title":"…","artist_display":"…"}}', "{ data: { id, title, image_id, … } }"),
  entry("uk-police-crimes", "data.police.uk — crimes near point", "Geography", "UK street-level crime", "Requires lat, lng, and YYYY-MM (use a recent month).", "https://data.police.uk/api/crimes-street/all-crime?lat=51.5074&lng=-0.1278&date=2024-01", "GET ?lat=&lng=&date=", '[{"category":"anti-social-behaviour","month":"2024-01"}]', "Array of { category, location_type, month, … }"),
  entry("exchangerate-host-latest", "exchangerate.host — latest rates", "Finance", "FX relative to base", "Latest conversion table for symbols list.", "https://api.exchangerate.host/latest?base=USD&symbols=EUR,GBP", "GET /latest?base=&symbols=", '{"success":true,"base":"USD","rates":{"EUR":0.92,"GBP":0.79}}', "{ success, base, date, rates }"),
  entry("shibe-online", "Shibe.online — Shiba images", "Fun", "Random doge URLs", "JSON array of image URLs.", "https://shibe.online/api/shibes?count=1&urls=true&httpsUrls=true", "GET ?count=&urls=", '["https://cdn.shibe.online/shibes/…"]', "string[] image URLs"),
  entry("dummyjson-product", "DummyJSON — product", "Dev & JSON", "E-commerce sample object", "Product with title, price, brand, images.", "https://dummyjson.com/products/1", "GET /products/{id}", '{"id":1,"title":"…","price":549,"brand":"…"}', "{ id, title, price, brand, images[], … }"),
  entry("fakestore-product", "FakeStoreAPI — product", "Dev & JSON", "Catalog item", "Clothing/electronics style mock inventory.", "https://fakestoreapi.com/products/1", "GET /products/{id}", '{"id":1,"title":"…","price":109.95,"category":"…"}', "{ id, title, price, category, image, … }"),
  entry("reqres-user", "Reqres — sample user", "Dev & JSON", "Test user resource", "Fake user for pagination and auth demos.", "https://reqres.in/api/users/2", "GET /api/users/{id}", '{"data":{"id":2,"email":"…","first_name":"Janet"}}', "{ data: { id, email, first_name, avatar } }"),
  entry("jp-todo", "JSONPlaceholder — todo", "Dev & JSON", "Single todo", "Completed flag and user linkage.", "https://jsonplaceholder.typicode.com/todos/1", "GET /todos/{id}", '{"userId":1,"id":1,"title":"…","completed":false}', "{ userId, id, title, completed }"),
  entry("jp-user", "JSONPlaceholder — user", "Dev & JSON", "User with address", "Nested address and geo for mapping demos.", "https://jsonplaceholder.typicode.com/users/1", "GET /users/{id}", '{"id":1,"name":"Leanne Graham","email":"…","address":{"city":"…"}}', "{ id, name, email, address: { city, geo } }"),
  entry("jp-album", "JSONPlaceholder — album", "Dev & JSON", "Album metadata", "Album id links to userId.", "https://jsonplaceholder.typicode.com/albums/1", "GET /albums/{id}", '{"userId":1,"id":1,"title":"…"}', "{ userId, id, title }"),
  entry("jp-photo", "JSONPlaceholder — photo", "Dev & JSON", "Photo with thumbnail URL", "Remote image URL fields.", "https://jsonplaceholder.typicode.com/photos/1", "GET /photos/{id}", '{"albumId":1,"id":1,"title":"…","url":"https://…"}', "{ albumId, id, title, url, thumbnailUrl }"),
  entry("restcountries-alpha", "REST Countries — by alpha-2", "Geography", "Single country by code", "ISO alpha-2 path segment.", "https://restcountries.com/v3.1/alpha/de", "GET /v3.1/alpha/{code}", '{"name":{"common":"Germany"},"cca2":"DE"}', "{ name, cca2, capital[], population, … }"),
  entry("openbrewery-search", "Open Brewery DB — search", "Food & drink", "US brewery list", "Text search across brewery names.", "https://api.openbrewerydb.org/v1/breweries?by_city=san_diego&per_page=3", "GET ?by_city=&per_page=", '[{"id":"…","name":"…","brewery_type":"micro"}]', "Array of { id, name, brewery_type, city, … }"),
  entry("animechan-random", "Animechan — random quote", "Entertainment", "Anime quote JSON", "Character and anime name included.", "https://animechan.xyz/api/random", "GET /api/random", '{"anime":"…","character":"…","quote":"…"}', "{ anime, character, quote }"),
  entry("jikan-anime", "Jikan — anime full", "Entertainment", "MyAnimeList mirror", "Unofficial MAL API; respect rate limits.", "https://api.jikan.moe/v4/anime/1/full", "GET /v4/anime/{id}/full", '{"data":{"mal_id":1,"title":"Cowboy Bebop","synopsis":"…"}}', "{ data: { mal_id, title, synopsis, … } }"),
  entry("finalspace-chars", "Final Space API — characters", "Entertainment", "Sci-fi character list", "Query limit for smaller payloads.", "https://finalspaceapi.com/api/v0/character?limit=2", "GET ?limit=", '[{"id":1,"name":"Gary Goodspeed"}]', "Array of { id, name, species, img, … }"),
  entry("breaking-bad-char", "Breaking Bad API — character search", "Entertainment", "Character by name", "Array of matches (may be empty).", "https://www.breakingbadapi.com/api/character?name=Walter+White", "GET ?name=", '[{"char_id":1,"name":"Walter White","nickname":"Heisenberg"}]', "Array of { char_id, name, occupation[], … }"),
  entry("swapi-film", "SWAPI — film", "Entertainment", "Episode metadata", "Opening crawl and character URLs.", "https://swapi.dev/api/films/1/", "GET /api/films/{id}/", '{"title":"A New Hope","episode_id":4,"director":"George Lucas"}', "{ title, episode_id, director, characters[], … }"),
  entry("swapi-starship", "SWAPI — starship", "Entertainment", "Ship stats as strings", "Crew, cargo, films links.", "https://swapi.dev/api/starships/9/", '{"name":"Death Star","model":"DS-1","crew":"342,953"}', "{ name, model, crew, films[], … }"),
  entry("pokeapi-berry", "PokeAPI — berry flavor", "Games", "Berry firmness & flavors", "Contest flavor potency map.", "https://pokeapi.co/api/v2/berry/1", "GET /api/v2/berry/{id}", '{"id":1,"name":"cheri","growth_time":3}', "{ id, name, growth_time, flavors[], … }"),
  entry("openfoodfacts-barcode", "Open Food Facts — product", "Food & drink", "Packaged food JSON", "Nutriments and labels by GTIN.", "https://world.openfoodfacts.org/api/v0/product/3017620422003.json", "GET /product/{code}.json", '{"status":1,"product":{"product_name":"…","nutriments":{}}}', "{ status, product: { product_name, nutriments, … } }"),
  entry("postman-echo-get", "Postman Echo — GET mirror", "Dev utilities", "Reflects query args", "Useful to verify proxy query forwarding.", "https://postman-echo.com/get?foo=bar&source=ghostapi", "GET /get?…", '{"args":{"foo":"bar","source":"ghostapi"}}', "{ args, headers, url }"),
  entry("httpbin-get", "HTTPBin — GET", "Dev utilities", "Request echo JSON", "Returns headers and origin as seen by server.", "https://httpbin.org/get", "GET /get", '{"origin":"…","headers":{"User-Agent":"…"}}', "{ origin, headers, url }"),
  entry("uselessfacts-random", "Useless Facts — random", "Fun", "Multilingual fact", "Random fact with permanent id.", "https://uselessfacts.jsph.pl/api/v1/facts/random?language=en", "GET ?language=", '{"id":"…","text":"…","language":"en"}', "{ id, text, language, source, … }"),
  entry("newton-factor", "Newton — math factorization", "Education", "Symbolic CAS JSON", "URL-encode expressions in the path.", "https://newton.vercel.app/api/v2/factor/x%5E2-1", "GET /api/v2/factor/{expr}", '{"operation":"factor","expression":"x^2-1","result":"(x - 1) (x + 1)"}', "{ operation, expression, result }"),
  entry("viacep-brazil", "ViaCEP — Brazilian postal code", "Geography", "CEP → address JSON", "Eight-digit CEP without hyphen in path.", "https://viacep.com.br/ws/01001000/json/", "GET /ws/{cep}/json/", '{"cep":"01001-000","logradouro":"…","localidade":"São Paulo","uf":"SP"}', "{ cep, logradouro, bairro, localidade, uf, … }"),
  entry("brasilapi-holidays", "Brasil API — national holidays", "Geography", "Brazil feriados by year", "Official holiday names and dates.", "https://brasilapi.com.br/api/feriados/v1/2024", "GET /api/feriados/v1/{year}", '[{"date":"2024-01-01","name":"Confraternização mundial"}]', "Array of { date, name, type }"),
  entry("random-fox", "Random Fox — image URL", "Fun", "Cute fox photo JSON", "Single image link per request.", "https://randomfox.ca/floof/", "GET /floof/", '{"image":"https://randomfox.ca/images/fox.jpg","link":"…"}', "{ image, link }"),
  entry("swapi-planet", "SWAPI — planet", "Entertainment", "Planet climate & terrain", "Population as string.", "https://swapi.dev/api/planets/1/", "GET /api/planets/{id}/", '{"name":"Tatooine","climate":"arid","population":"200000"}', "{ name, climate, terrain, population, … }"),
  entry("swapi-vehicle", "SWAPI — vehicle", "Entertainment", "Ground vehicle", "Manufacturer and length fields.", "https://swapi.dev/api/vehicles/4/", "GET /api/vehicles/{id}/", '{"name":"Sand Crawler","vehicle_class":"wheeled"}', "{ name, model, vehicle_class, passengers, … }"),
  entry("swapi-species", "SWAPI — species", "Entertainment", "Alien species", "Classification and homeworld URL.", "https://swapi.dev/api/species/1/", '{"name":"Human","classification":"mammal"}', "{ name, classification, average_height, homeworld, … }"),
  entry("jp-comments", "JSONPlaceholder — post comments", "Dev & JSON", "All comments for post 1", "Array of email + body.", "https://jsonplaceholder.typicode.com/posts/1/comments", "GET /posts/{id}/comments", '[{"postId":1,"id":1,"email":"…","body":"…"}]', "Array of { postId, id, name, email, body }"),
  entry("pokeapi-type-fire", "PokeAPI — type Fire", "Games", "Type relations graph", "Damage multipliers vs other types.", "https://pokeapi.co/api/v2/type/10", "GET /api/v2/type/{id}", '{"id":10,"name":"fire","damage_relations":{}}', "{ id, name, damage_relations: { double_damage_to[], … } }"),
  entry("pokeapi-ability", "PokeAPI — ability Stench", "Games", "Ability effect text", "Verbose effect entries per language.", "https://pokeapi.co/api/v2/ability/1", "GET /api/v2/ability/{id}", '{"id":1,"name":"stench","effect_entries":[]}', "{ id, name, effect_entries[], pokemon[], … }"),
];

function entry(
  slug: string,
  name: string,
  category: string,
  tagline: string,
  description: string,
  exampleUrl: string,
  requestExample: string,
  responseExample: string,
  responseShape: string
): CuratedApiEntry {
  return {
    slug,
    name,
    category,
    tagline,
    description,
    auth: "none",
    defaultMethod: "GET",
    exampleUrl,
    requestNotes: `Use HTTPS GET unless the provider documents POST. Example: ${requestExample}`,
    requestExample,
    responseExample,
    responseShape,
  };
}
